INSERT INTO --CountryName-- VALUES (1, 'US', 'United States', 'US.png', '1');
INSERT INTO --CountryName-- VALUES (2, 'CA', 'Canada', 'CA.png', '1');
INSERT INTO --CountryName-- VALUES (3, 'AF', 'Afghanistan', 'AF.png', '1');
INSERT INTO --CountryName-- VALUES (4, 'AL', 'Albania', 'AL.png', '1');
INSERT INTO --CountryName-- VALUES (5, 'DZ', 'Algeria', 'DZ.png', '1');
INSERT INTO --CountryName-- VALUES (6, 'DS', 'American Samoa', 'AS.png', '1');
INSERT INTO --CountryName-- VALUES (7, 'AD', 'Andorra', 'AD.png', '1');
INSERT INTO --CountryName-- VALUES (8, 'AO', 'Angola', 'AO.png', '1');
INSERT INTO --CountryName-- VALUES (9, 'AI', 'Anguilla', 'AI.png', '1');
INSERT INTO --CountryName-- VALUES (10, 'AQ', 'Antarctica', 'AQ.png', '1');
INSERT INTO --CountryName-- VALUES (11, 'AG', 'Antigua and/or Barbuda', '', '1');
INSERT INTO --CountryName-- VALUES (12, 'AR', 'Argentina', 'AR.png', '1');
INSERT INTO --CountryName-- VALUES (13, 'AM', 'Armenia', 'AM.png', '1');
INSERT INTO --CountryName-- VALUES (14, 'AW', 'Aruba', 'AW.png', '1');
INSERT INTO --CountryName-- VALUES (15, 'AU', 'Australia', 'AU.png', '1');
INSERT INTO --CountryName-- VALUES (16, 'AT', 'Austria', 'AT.png', '1');
INSERT INTO --CountryName-- VALUES (17, 'AZ', 'Azerbaijan', 'AZ.png', '1');
INSERT INTO --CountryName-- VALUES (18, 'BS', 'Bahamas', 'BS.png', '1');
INSERT INTO --CountryName-- VALUES (19, 'BH', 'Bahrain', 'BH.png', '1');
INSERT INTO --CountryName-- VALUES (20, 'BD', 'Bangladesh', 'BD.png', '1');
INSERT INTO --CountryName-- VALUES (21, 'BB', 'Barbados', 'BB.png', '1');
INSERT INTO --CountryName-- VALUES (22, 'BY', 'Belarus', 'BY.png', '1');
INSERT INTO --CountryName-- VALUES (23, 'BE', 'Belgium', 'BE.png', '1');
INSERT INTO --CountryName-- VALUES (24, 'BZ', 'Belize', 'BZ.png', '1');
INSERT INTO --CountryName-- VALUES (25, 'BJ', 'Benin', 'BJ.png', '1');
INSERT INTO --CountryName-- VALUES (26, 'BM', 'Bermuda', 'BM.png', '1');
INSERT INTO --CountryName-- VALUES (27, 'BT', 'Bhutan', 'BT.png', '1');
INSERT INTO --CountryName-- VALUES (28, 'BO', 'Bolivia', 'BO.png', '1');
INSERT INTO --CountryName-- VALUES (29, 'BA', 'Bosnia and Herzegovina', 'BA.png', '1');
INSERT INTO --CountryName-- VALUES (30, 'BW', 'Botswana', 'BW.png', '1');
INSERT INTO --CountryName-- VALUES (31, 'BV', 'Bouvet Island', 'BV.png', '1');
INSERT INTO --CountryName-- VALUES (32, 'BR', 'Brazil', 'BR.png', '1');
INSERT INTO --CountryName-- VALUES (33, 'IO', 'British lndian Ocean Territory', '', '1');
INSERT INTO --CountryName-- VALUES (34, 'BN', 'Brunei Darussalam', '', '1');
INSERT INTO --CountryName-- VALUES (35, 'BG', 'Bulgaria', 'BG.png', '1');
INSERT INTO --CountryName-- VALUES (36, 'BF', 'Burkina Faso', 'BF.png', '1');
INSERT INTO --CountryName-- VALUES (37, 'BI', 'Burundi', 'BI.png', '1');
INSERT INTO --CountryName-- VALUES (38, 'KH', 'Cambodia', 'KH.png', '1');
INSERT INTO --CountryName-- VALUES (39, 'CM', 'Cameroon', 'CM.png', '1');
INSERT INTO --CountryName-- VALUES (40, 'CV', 'Cape Verde', 'CV.png', '1');
INSERT INTO --CountryName-- VALUES (41, 'KY', 'Cayman Islands', 'KY.png', '1');
INSERT INTO --CountryName-- VALUES (42, 'CF', 'Central African Republic', 'CF.png', '1');
INSERT INTO --CountryName-- VALUES (43, 'TD', 'Chad', 'TD.png', '1');
INSERT INTO --CountryName-- VALUES (44, 'CL', 'Chile', 'CL.png', '1');
INSERT INTO --CountryName-- VALUES (45, 'CN', 'China', 'CN.png', '1');
INSERT INTO --CountryName-- VALUES (46, 'CX', 'Christmas Island', 'CX.png', '1');
INSERT INTO --CountryName-- VALUES (47, 'CC', 'Cocos (Keeling) Islands', '', '1');
INSERT INTO --CountryName-- VALUES (48, 'CO', 'Colombia', 'CO.png', '1');
INSERT INTO --CountryName-- VALUES (49, 'KM', 'Comoros', 'KM.png', '1');
INSERT INTO --CountryName-- VALUES (50, 'CG', 'Congo', '', '1');
INSERT INTO --CountryName-- VALUES (51, 'CK', 'Cook Islands', 'CK.png', '1');
INSERT INTO --CountryName-- VALUES (52, 'CR', 'Costa Rica', 'CR.png', '1');
INSERT INTO --CountryName-- VALUES (53, 'HR', 'Croatia (Hrvatska)', '', '1');
INSERT INTO --CountryName-- VALUES (54, 'CU', 'Cuba', 'CU.png', '1');
INSERT INTO --CountryName-- VALUES (55, 'CY', 'Cyprus', 'CY.png', '1');
INSERT INTO --CountryName-- VALUES (56, 'CZ', 'Czech Republic', 'CZ.png', '1');
INSERT INTO --CountryName-- VALUES (57, 'DK', 'Denmark', 'DK.png', '1');
INSERT INTO --CountryName-- VALUES (58, 'DJ', 'Djibouti', 'DJ.png', '1');
INSERT INTO --CountryName-- VALUES (59, 'DM', 'Dominica', 'DM.png', '1');
INSERT INTO --CountryName-- VALUES (60, 'DO', 'Dominican Republic', 'DO.png', '1');
INSERT INTO --CountryName-- VALUES (61, 'TP', 'East Timor', 'TL.png', '1');
INSERT INTO --CountryName-- VALUES (62, 'EC', 'Ecuador', 'EC.png', '1');
INSERT INTO --CountryName-- VALUES (63, 'EG', 'Egypt', 'EG.png', '1');
INSERT INTO --CountryName-- VALUES (64, 'SV', 'El Salvador', 'SV.png', '1');
INSERT INTO --CountryName-- VALUES (65, 'GQ', 'Equatorial Guinea', 'GQ.png', '1');
INSERT INTO --CountryName-- VALUES (66, 'ER', 'Eritrea', 'ER.png', '1');
INSERT INTO --CountryName-- VALUES (67, 'EE', 'Estonia', 'EE.png', '1');
INSERT INTO --CountryName-- VALUES (68, 'ET', 'Ethiopia', 'ET.png', '1');
INSERT INTO --CountryName-- VALUES (69, 'FK', 'Falkland Islands (Malvinas)', 'FK.png', '1');
INSERT INTO --CountryName-- VALUES (70, 'FO', 'Faroe Islands', 'FO.png', '1');
INSERT INTO --CountryName-- VALUES (71, 'FJ', 'Fiji', 'FJ.png', '1');
INSERT INTO --CountryName-- VALUES (72, 'FI', 'Finland', 'FI.png', '1');
INSERT INTO --CountryName-- VALUES (73, 'FR', 'France', 'FR.png', '1');
INSERT INTO --CountryName-- VALUES (74, 'FX', 'France, Metropolitan', '', '1');
INSERT INTO --CountryName-- VALUES (75, 'GF', 'French Guiana', 'GF.png', '1');
INSERT INTO --CountryName-- VALUES (76, 'PF', 'French Polynesia', 'PF.png', '1');
INSERT INTO --CountryName-- VALUES (77, 'TF', 'French Southern Territories', 'TF.png', '1');
INSERT INTO --CountryName-- VALUES (78, 'GA', 'Gabon', 'GA.png', '1');
INSERT INTO --CountryName-- VALUES (79, 'GM', 'Gambia', 'GM.png', '1');
INSERT INTO --CountryName-- VALUES (80, 'GE', 'Georgia', 'GE.png', '1');
INSERT INTO --CountryName-- VALUES (81, 'DE', 'Germany', 'DE.png', '1');
INSERT INTO --CountryName-- VALUES (82, 'GH', 'Ghana', 'GH.png', '1');
INSERT INTO --CountryName-- VALUES (83, 'GI', 'Gibraltar', 'GI.png', '1');
INSERT INTO --CountryName-- VALUES (84, 'GR', 'Greece', 'GR.png', '1');
INSERT INTO --CountryName-- VALUES (85, 'GL', 'Greenland', 'GL.png', '1');
INSERT INTO --CountryName-- VALUES (86, 'GD', 'Grenada', 'GD.png', '1');
INSERT INTO --CountryName-- VALUES (87, 'GP', 'Guadeloupe', 'GP.png', '1');
INSERT INTO --CountryName-- VALUES (88, 'GU', 'Guam', 'GU.png', '1');
INSERT INTO --CountryName-- VALUES (89, 'GT', 'Guatemala', 'GT.png', '1');
INSERT INTO --CountryName-- VALUES (90, 'GN', 'Guinea', 'GN.png', '1');
INSERT INTO --CountryName-- VALUES (91, 'GW', 'Guinea-Bissau', 'GW.png', '1');
INSERT INTO --CountryName-- VALUES (92, 'GY', 'Guyana', 'GY.png', '1');
INSERT INTO --CountryName-- VALUES (93, 'HT', 'Haiti', 'HT.png', '1');
INSERT INTO --CountryName-- VALUES (94, 'HM', 'Heard and Mc Donald Islands', '', '1');
INSERT INTO --CountryName-- VALUES (95, 'HN', 'Honduras', 'HN.png', '1');
INSERT INTO --CountryName-- VALUES (96, 'HK', 'Hong Kong', 'HK.png', '1');
INSERT INTO --CountryName-- VALUES (97, 'HU', 'Hungary', 'HU.png', '1');
INSERT INTO --CountryName-- VALUES (98, 'IS', 'Iceland', 'IS.png', '1');
INSERT INTO --CountryName-- VALUES (99, 'IN', 'India', 'IN.png', '1');
INSERT INTO --CountryName-- VALUES (100, 'ID', 'Indonesia', 'ID.png', '1');
INSERT INTO --CountryName-- VALUES (101, 'IR', 'Iran (Islamic Republic of)', '', '1');
INSERT INTO --CountryName-- VALUES (102, 'IQ', 'Iraq', 'IQ.png', '1');
INSERT INTO --CountryName-- VALUES (103, 'IE', 'Ireland', 'IE.png', '1');
INSERT INTO --CountryName-- VALUES (104, 'IL', 'Israel', 'IL.png', '1');
INSERT INTO --CountryName-- VALUES (105, 'IT', 'Italy', 'IT.png', '1');
INSERT INTO --CountryName-- VALUES (106, 'CI', 'Ivory Coast', 'CI.png', '1');
INSERT INTO --CountryName-- VALUES (107, 'JM', 'Jamaica', 'JM.png', '1');
INSERT INTO --CountryName-- VALUES (108, 'JP', 'Japan', 'JP.png', '1');
INSERT INTO --CountryName-- VALUES (109, 'JO', 'Jordan', 'JO.png', '1');
INSERT INTO --CountryName-- VALUES (110, 'KZ', 'Kazakhstan', 'KZ.png', '1');
INSERT INTO --CountryName-- VALUES (111, 'KE', 'Kenya', 'KE.png', '1');
INSERT INTO --CountryName-- VALUES (112, 'KI', 'Kiribati', 'KI.png', '1');
INSERT INTO --CountryName-- VALUES (113, 'KP', 'Korea, Democratic People''s Republic of', '', '1');
INSERT INTO --CountryName-- VALUES (114, 'KR', 'Korea, Republic of', '', '1');
INSERT INTO --CountryName-- VALUES (115, 'XK', 'Kosovo', '', '1');
INSERT INTO --CountryName-- VALUES (116, 'KW', 'Kuwait', 'KW.png', '1');
INSERT INTO --CountryName-- VALUES (117, 'KG', 'Kyrgyzstan', 'KG.png', '1');
INSERT INTO --CountryName-- VALUES (118, 'LA', 'Lao People''s Democratic Republic', '', '1');
INSERT INTO --CountryName-- VALUES (119, 'LV', 'Latvia', 'LV.png', '1');
INSERT INTO --CountryName-- VALUES (120, 'LB', 'Lebanon', 'LB.png', '1');
INSERT INTO --CountryName-- VALUES (121, 'LS', 'Lesotho', 'LS.png', '1');
INSERT INTO --CountryName-- VALUES (122, 'LR', 'Liberia', 'LR.png', '1');
INSERT INTO --CountryName-- VALUES (123, 'LY', 'Libyan Arab Jamahiriya', '', '1');
INSERT INTO --CountryName-- VALUES (124, 'LI', 'Liechtenstein', 'LI.png', '1');
INSERT INTO --CountryName-- VALUES (125, 'LT', 'Lithuania', 'LT.png', '1');
INSERT INTO --CountryName-- VALUES (126, 'LU', 'Luxembourg', 'LU.png', '1');
INSERT INTO --CountryName-- VALUES (127, 'MO', 'Macau', '', '1');
INSERT INTO --CountryName-- VALUES (128, 'MK', 'Macedonia', 'MK.png', '1');
INSERT INTO --CountryName-- VALUES (129, 'MG', 'Madagascar', 'MG.png', '1');
INSERT INTO --CountryName-- VALUES (130, 'MW', 'Malawi', 'MW.png', '1');
INSERT INTO --CountryName-- VALUES (131, 'MY', 'Malaysia', 'MY.png', '1');
INSERT INTO --CountryName-- VALUES (132, 'MV', 'Maldives', 'MV.png', '1');
INSERT INTO --CountryName-- VALUES (133, 'ML', 'Mali', 'ML.png', '1');
INSERT INTO --CountryName-- VALUES (134, 'MT', 'Malta', 'MT.png', '1');
INSERT INTO --CountryName-- VALUES (135, 'MH', 'Marshall Islands', 'MH.png', '1');
INSERT INTO --CountryName-- VALUES (136, 'MQ', 'Martinique', 'MQ.png', '1');
INSERT INTO --CountryName-- VALUES (137, 'MR', 'Mauritania', 'MR.png', '1');
INSERT INTO --CountryName-- VALUES (138, 'MU', 'Mauritius', 'MU.png', '1');
INSERT INTO --CountryName-- VALUES (139, 'TY', 'Mayotte', 'YT.png', '1');
INSERT INTO --CountryName-- VALUES (140, 'MX', 'Mexico', 'MX.png', '1');
INSERT INTO --CountryName-- VALUES (141, 'FM', 'Micronesia, Federated States of', '', '1');
INSERT INTO --CountryName-- VALUES (142, 'MD', 'Moldova, Republic of', '', '1');
INSERT INTO --CountryName-- VALUES (143, 'MC', 'Monaco', 'MC.png', '1');
INSERT INTO --CountryName-- VALUES (144, 'MN', 'Mongolia', 'MN.png', '1');
INSERT INTO --CountryName-- VALUES (145, 'ME', 'Montenegro', '', '1');
INSERT INTO --CountryName-- VALUES (146, 'MS', 'Montserrat', 'MS.png', '1');
INSERT INTO --CountryName-- VALUES (147, 'MA', 'Morocco', 'MA.png', '1');
INSERT INTO --CountryName-- VALUES (148, 'MZ', 'Mozambique', 'MZ.png', '1');
INSERT INTO --CountryName-- VALUES (149, 'MM', 'Myanmar', 'MM.png', '1');
INSERT INTO --CountryName-- VALUES (150, 'NA', 'Namibia', 'NA.png', '1');
INSERT INTO --CountryName-- VALUES (151, 'NR', 'Nauru', 'NR.png', '1');
INSERT INTO --CountryName-- VALUES (152, 'NP', 'Nepal', 'NP.png', '1');
INSERT INTO --CountryName-- VALUES (153, 'NL', 'Netherlands', 'NL.png', '1');
INSERT INTO --CountryName-- VALUES (154, 'AN', 'Netherlands Antilles', 'AN.png', '1');
INSERT INTO --CountryName-- VALUES (155, 'NC', 'New Caledonia', 'NC.png', '1');
INSERT INTO --CountryName-- VALUES (156, 'NZ', 'New Zealand', 'NZ.png', '1');
INSERT INTO --CountryName-- VALUES (157, 'NI', 'Nicaragua', 'NI.png', '1');
INSERT INTO --CountryName-- VALUES (158, 'NE', 'Niger', 'NE.png', '1');
INSERT INTO --CountryName-- VALUES (159, 'NG', 'Nigeria', 'NG.png', '1');
INSERT INTO --CountryName-- VALUES (160, 'NU', 'Niue', 'NU.png', '1');
INSERT INTO --CountryName-- VALUES (161, 'NF', 'Norfork Island', '', '1');
INSERT INTO --CountryName-- VALUES (162, 'MP', 'Northern Mariana Islands', 'MP.png', '1');
INSERT INTO --CountryName-- VALUES (163, 'NO', 'Norway', 'NO.png', '1');
INSERT INTO --CountryName-- VALUES (164, 'OM', 'Oman', 'OM.png', '1');
INSERT INTO --CountryName-- VALUES (165, 'PK', 'Pakistan', 'PK.png', '1');
INSERT INTO --CountryName-- VALUES (166, 'PW', 'Palau', 'PW.png', '1');
INSERT INTO --CountryName-- VALUES (167, 'PA', 'Panama', 'PA.png', '1');
INSERT INTO --CountryName-- VALUES (168, 'PG', 'Papua New Guinea', 'PG.png', '1');
INSERT INTO --CountryName-- VALUES (169, 'PY', 'Paraguay', 'PY.png', '1');
INSERT INTO --CountryName-- VALUES (170, 'PE', 'Peru', 'PE.png', '1');
INSERT INTO --CountryName-- VALUES (171, 'PH', 'Philippines', 'PH.png', '1');
INSERT INTO --CountryName-- VALUES (172, 'PN', 'Pitcairn', 'PN.png', '1');
INSERT INTO --CountryName-- VALUES (173, 'PL', 'Poland', 'PL.png', '1');
INSERT INTO --CountryName-- VALUES (174, 'PT', 'Portugal', 'PT.png', '1');
INSERT INTO --CountryName-- VALUES (175, 'PR', 'Puerto Rico', 'PR.png', '1');
INSERT INTO --CountryName-- VALUES (176, 'QA', 'Qatar', 'QA.png', '1');
INSERT INTO --CountryName-- VALUES (177, 'RE', 'Reunion', 'RE.png', '1');
INSERT INTO --CountryName-- VALUES (178, 'RO', 'Romania', 'RO.png', '1');
INSERT INTO --CountryName-- VALUES (179, 'RU', 'Russian Federation', '', '1');
INSERT INTO --CountryName-- VALUES (180, 'RW', 'Rwanda', 'RW.png', '1');
INSERT INTO --CountryName-- VALUES (181, 'KN', 'Saint Kitts and Nevis', 'KN.png', '1');
INSERT INTO --CountryName-- VALUES (182, 'LC', 'Saint Lucia', 'LC.png', '1');
INSERT INTO --CountryName-- VALUES (183, 'VC', 'Saint Vincent and the Grenadines', 'VC.png', '1');
INSERT INTO --CountryName-- VALUES (184, 'WS', 'Samoa', 'WS.png', '1');
INSERT INTO --CountryName-- VALUES (185, 'SM', 'San Marino', 'SM.png', '1');
INSERT INTO --CountryName-- VALUES (186, 'ST', 'Sao Tome and Principe', 'ST.png', '1');
INSERT INTO --CountryName-- VALUES (187, 'SA', 'Saudi Arabia', 'SA.png', '1');
INSERT INTO --CountryName-- VALUES (188, 'SN', 'Senegal', 'SN.png', '1');
INSERT INTO --CountryName-- VALUES (189, 'RS', 'Serbia', '', '1');
INSERT INTO --CountryName-- VALUES (190, 'SC', 'Seychelles', 'SC.png', '1');
INSERT INTO --CountryName-- VALUES (191, 'SL', 'Sierra Leone', 'SL.png', '1');
INSERT INTO --CountryName-- VALUES (192, 'SG', 'Singapore', 'SG.png', '1');
INSERT INTO --CountryName-- VALUES (193, 'SK', 'Slovakia', 'SK.png', '1');
INSERT INTO --CountryName-- VALUES (194, 'SI', 'Slovenia', 'SI.png', '1');
INSERT INTO --CountryName-- VALUES (195, 'SB', 'Solomon Islands', 'SB.png', '1');
INSERT INTO --CountryName-- VALUES (196, 'SO', 'Somalia', 'SO.png', '1');
INSERT INTO --CountryName-- VALUES (197, 'ZA', 'South Africa', 'ZA.png', '1');
INSERT INTO --CountryName-- VALUES (198, 'GS', 'South Georgia South Sandwich Islands', '', '1');
INSERT INTO --CountryName-- VALUES (199, 'ES', 'Spain', 'ES.png', '1');
INSERT INTO --CountryName-- VALUES (200, 'LK', 'Sri Lanka', 'LK.png', '1');
INSERT INTO --CountryName-- VALUES (201, 'SH', 'St. Helena', '', '1');
INSERT INTO --CountryName-- VALUES (202, 'PM', 'St. Pierre and Miquelon', '', '1');
INSERT INTO --CountryName-- VALUES (203, 'SD', 'Sudan', 'SD.png', '1');
INSERT INTO --CountryName-- VALUES (204, 'SR', 'Suriname', 'SR.png', '1');
INSERT INTO --CountryName-- VALUES (205, 'SJ', 'Svalbarn and Jan Mayen Islands', '', '1');
INSERT INTO --CountryName-- VALUES (206, 'SZ', 'Swaziland', 'SZ.png', '1');
INSERT INTO --CountryName-- VALUES (207, 'SE', 'Sweden', 'SE.png', '1');
INSERT INTO --CountryName-- VALUES (208, 'CH', 'Switzerland', 'CH.png', '1');
INSERT INTO --CountryName-- VALUES (209, 'SY', 'Syrian Arab Republic', '', '1');
INSERT INTO --CountryName-- VALUES (210, 'TW', 'Taiwan', 'TW.png', '1');
INSERT INTO --CountryName-- VALUES (211, 'TJ', 'Tajikistan', 'TJ.png', '1');
INSERT INTO --CountryName-- VALUES (212, 'TZ', 'Tanzania, United Republic of', '', '1');
INSERT INTO --CountryName-- VALUES (213, 'TH', 'Thailand', 'TH.png', '1');
INSERT INTO --CountryName-- VALUES (214, 'TG', 'Togo', 'TG.png', '1');
INSERT INTO --CountryName-- VALUES (215, 'TK', 'Tokelau', 'TK.png', '1');
INSERT INTO --CountryName-- VALUES (216, 'TO', 'Tonga', 'TO.png', '1');
INSERT INTO --CountryName-- VALUES (217, 'TT', 'Trinidad and Tobago', 'TT.png', '1');
INSERT INTO --CountryName-- VALUES (218, 'TN', 'Tunisia', 'TN.png', '1');
INSERT INTO --CountryName-- VALUES (219, 'TR', 'Turkey', 'TR.png', '1');
INSERT INTO --CountryName-- VALUES (220, 'TM', 'Turkmenistan', 'TM.png', '1');
INSERT INTO --CountryName-- VALUES (221, 'TC', 'Turks and Caicos Islands', 'TC.png', '1');
INSERT INTO --CountryName-- VALUES (222, 'TV', 'Tuvalu', 'TV.png', '1');
INSERT INTO --CountryName-- VALUES (223, 'UG', 'Uganda', 'UG.png', '1');
INSERT INTO --CountryName-- VALUES (224, 'UA', 'Ukraine', 'UA.png', '1');
INSERT INTO --CountryName-- VALUES (225, 'AE', 'United Arab Emirates', 'AE.png', '1');
INSERT INTO --CountryName-- VALUES (226, 'GB', 'United Kingdom', 'GB.png', '1');
INSERT INTO --CountryName-- VALUES (227, 'UM', 'United States minor outlying islands', 'UM.png', '1');
INSERT INTO --CountryName-- VALUES (228, 'UY', 'Uruguay', 'UY.png', '1');
INSERT INTO --CountryName-- VALUES (229, 'UZ', 'Uzbekistan', 'UZ.png', '1');
INSERT INTO --CountryName-- VALUES (230, 'VU', 'Vanuatu', 'VU.png', '1');
INSERT INTO --CountryName-- VALUES (231, 'VA', 'Vatican City State', '', '1');
INSERT INTO --CountryName-- VALUES (232, 'VE', 'Venezuela', 'VE.png', '1');
INSERT INTO --CountryName-- VALUES (233, 'VN', 'Vietnam', 'VN.png', '1');
INSERT INTO --CountryName-- VALUES (234, 'VG', 'Virigan Islands (British)', '', '1');
INSERT INTO --CountryName-- VALUES (235, 'VI', 'Virgin Islands (U.S.)', '', '1');
INSERT INTO --CountryName-- VALUES (236, 'WF', 'Wallis and Futuna Islands', '', '1');
INSERT INTO --CountryName-- VALUES (237, 'EH', 'Western Sahara', 'EH.png', '1');
INSERT INTO --CountryName-- VALUES (238, 'YE', 'Yemen', 'YE.png', '1');
INSERT INTO --CountryName-- VALUES (239, 'YU', 'Yugoslavia', '', '1');
INSERT INTO --CountryName-- VALUES (240, 'ZR', 'Zaire', '', '1');
INSERT INTO --CountryName-- VALUES (241, 'ZM', 'Zambia', 'ZM.png', '1');
INSERT INTO --CountryName-- VALUES (242, 'ZW', 'Zimbabwe', 'ZW.png', '1');
